In [1]:
import pandas as pd

/var/folders/h1/rvjbcw3x19dcwnv6qxb4pxrm0000gn/T/ipykernel_45058/4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [18]:
import pandera as pa
from pandera import DataFrameSchema, Column, Check


# Define the schema for the data
input_data_schema = DataFrameSchema(
    {
        'CompNo': Column(str, nullable=False, coerce=True),
        'StkIndx': Column(float, nullable=True, coerce=True),
        'STInt': Column(float, nullable=False, coerce=True),
        'dtdlevel': Column(float, nullable=True, coerce=True),
        'dtdtrend': Column(float, nullable=True, coerce=True),
        'liqnonfinlevel': Column(float, nullable=True, coerce=True),
        'liqnonfintrend': Column(float, nullable=True, coerce=True),
        'ni2talevel': Column(float, nullable=True, coerce=True),
        'ni2tatrend': Column(float, nullable=True, coerce=True),
        'sizelevel': Column(float, nullable=True, coerce=True),
        'sizetrend': Column(float, nullable=True, coerce=True),
        'm2b': Column(float, nullable=True, coerce=True),
        'sigma': Column(float, nullable=True, coerce=True),
        'DTDmedianNonFin': Column(float, nullable=True, coerce=True),
        'Company_name': Column(str, nullable=False, coerce=True),
        'INDUSTRY2': Column(str, nullable=True, coerce=True),
        'Date': Column(pa.DateTime, nullable=False, coerce=True),
        'Y': Column(pa.Category, checks=pa.Check.isin([0,1]), nullable=False, coerce=True),
        
    }
)

In [8]:
df = pd.read_csv("../data/input.csv")
df

,CompNo,StkIndx,STInt,dtdlevel,dtdtrend,liqnonfinlevel,liqnonfintrend,ni2talevel,ni2tatrend,sizelevel,sizetrend,m2b,sigma,DTDmedianNonFin,Company_name,INDUSTRY2,Date,Y
0,27014,0.133740,-0.011305,NaN,NaN,NaN,NaN,NaN,NaN,0.098522,0.000000,NaN,NaN,4.439600,FutureFuel Corp,131110.0,3/31/2011,0
1,27014,0.129957,-0.011527,NaN,NaN,NaN,NaN,NaN,NaN,0.171694,0.073172,NaN,NaN,4.525509,FutureFuel Corp,131110.0,4/30/2011,0
2,27014,0.232883,-0.011487,NaN,NaN,1.731534,0.0,0.002657,0.0,0.211718,0.080046,1.351018,NaN,4.615192,FutureFuel Corp,131110.0,5/31/2011,0
3,27014,0.281292,-0.011628,9.838830,0.000000,1.731534,0.0,0.002657,0.0,0.194665,-0.051159,1.238226,0.08823,4.581457,FutureFuel Corp,131110.0,6/30/2011,0
4,27014,0.173168,-0.011304,10.160107,0.321278,1.731534,0.0,0.002657,0.0,0.182296,-0.049475,1.286089,0.08193,4.557544,FutureFuel Corp,131110.0,7/31/2011,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138840,212613,0.239149,0.009543,NaN,NaN,NaN,NaN,NaN,NaN,1.268367,-0.022306,NaN,0.43358,3.316397,Atlas Energy Solutions Inc,131011.0,12/31/2023,0
138841,212750,0.083115,0.010061,NaN,NaN,NaN,NaN,NaN,NaN,1.271260,0.000000,NaN,NaN,2.963553,Mach Natural Resources LP,131010.0,10/31/2023,0
138842,212750,0.119529,0.009763,NaN,NaN,NaN,NaN,NaN,NaN,1.252952,-0.018307,NaN,NaN,3.119818,Mach Natural Resources LP,131010.0,11/30/2023,0
138843,212750,0.239149,0.009543,NaN,NaN,NaN,NaN,NaN,NaN,1.219033,-0.067838,NaN,NaN,3.316397,Mach Natural Resources LP,131010.0,12/31/2023,0
138844,213058,0.239149,0.009543,NaN,NaN,NaN,NaN,NaN,NaN,-1.181424,0.000000,NaN,NaN,3.316397,Vast Solar Pty Ltd,131110.0,12/31/2023,0

In [10]:
df.isna().sum()

CompNo                 0
StkIndx             1991
STInt                  0
dtdlevel           14551
dtdtrend           14551
liqnonfinlevel     16952
liqnonfintrend     16952
ni2talevel          8953
ni2tatrend          8953
sizelevel           1949
sizetrend           1949
m2b                 9145
sigma               6969
DTDmedianNonFin     6500
Company_name           0
INDUSTRY2             34
Date                   0
Y                      0
dtype: int64

In [19]:
input_data_schema.validate(df)

,CompNo,StkIndx,STInt,dtdlevel,dtdtrend,liqnonfinlevel,liqnonfintrend,ni2talevel,ni2tatrend,sizelevel,sizetrend,m2b,sigma,DTDmedianNonFin,Company_name,INDUSTRY2,Date,Y
0,27014,0.133740,-0.011305,NaN,NaN,NaN,NaN,NaN,NaN,0.098522,0.000000,NaN,NaN,4.439600,FutureFuel Corp,131110.0,2011-03-31,0
1,27014,0.129957,-0.011527,NaN,NaN,NaN,NaN,NaN,NaN,0.171694,0.073172,NaN,NaN,4.525509,FutureFuel Corp,131110.0,2011-04-30,0
2,27014,0.232883,-0.011487,NaN,NaN,1.731534,0.0,0.002657,0.0,0.211718,0.080046,1.351018,NaN,4.615192,FutureFuel Corp,131110.0,2011-05-31,0
3,27014,0.281292,-0.011628,9.838830,0.000000,1.731534,0.0,0.002657,0.0,0.194665,-0.051159,1.238226,0.08823,4.581457,FutureFuel Corp,131110.0,2011-06-30,0
4,27014,0.173168,-0.011304,10.160107,0.321278,1.731534,0.0,0.002657,0.0,0.182296,-0.049475,1.286089,0.08193,4.557544,FutureFuel Corp,131110.0,2011-07-31,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138840,212613,0.239149,0.009543,NaN,NaN,NaN,NaN,NaN,NaN,1.268367,-0.022306,NaN,0.43358,3.316397,Atlas Energy Solutions Inc,131011.0,2023-12-31,0
138841,212750,0.083115,0.010061,NaN,NaN,NaN,NaN,NaN,NaN,1.271260,0.000000,NaN,NaN,2.963553,Mach Natural Resources LP,131010.0,2023-10-31,0
138842,212750,0.119529,0.009763,NaN,NaN,NaN,NaN,NaN,NaN,1.252952,-0.018307,NaN,NaN,3.119818,Mach Natural Resources LP,131010.0,2023-11-30,0
138843,212750,0.239149,0.009543,NaN,NaN,NaN,NaN,NaN,NaN,1.219033,-0.067838,NaN,NaN,3.316397,Mach Natural Resources LP,131010.0,2023-12-31,0
138844,213058,0.239149,0.009543,NaN,NaN,NaN,NaN,NaN,NaN,-1.181424,0.000000,NaN,NaN,3.316397,Vast Solar Pty Ltd,131110.0,2023-12-31,0